// Generated by CoffeeScript 1.7.1
'use strict';

/**
  * @ngdoc function
  * @name frontendApp.controller:AboutCtrl
  * @description
  * # AboutCtrl
  * Controller of the frontendApp
 */
angular.module('grouptionApp').controller('AboutCtrl', function($scope) {
  return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
});
