// Generated by CoffeeScript 1.7.1
'use strict';

/**
  * @ngdoc function
  * @name frontendApp.controller:MainCtrl
  * @description
  * # MainCtrl
  * Controller of the frontendApp
 */
angular.module('grouptionApp').controller('MainCtrl', function($scope) {
  return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
});
