// Generated by CoffeeScript 1.7.1
'use strict';

/**
  * @ngdoc overview
  * @name frontendApp
  * @description
  * # frontendApp
  *
  * Main module of the application.
 */
angular.module('grouptionApp', ['ngAnimate', 'ngCookies', 'ngResource', 'ngRoute', 'ngSanitize', 'ngTouch']).config(function($routeProvider) {
  return $routeProvider.when('/', {
    templateUrl: 'views/main.html',
    controller: 'MainCtrl'
  }).when('/about', {
    templateUrl: 'views/about.html',
    controller: 'AboutCtrl'
  }).when('/users', {
    templateUrl: 'views/user.html',
    controller: 'UserController'
  }).otherwise({
    redirectTo: '/'
  });
});
