// Generated by CoffeeScript 1.7.1
'use strict';

/**
  * @ngdoc service
  * @name frontendApp.user
  * @description
  * # user
  * Service in the frontendApp.
 */
angular.module('grouptionApp').service('User', function() {
  return {
    getAllUsers: function() {
      return console.log('aqui generamos la consulta a nuestra API');
    },
    getUserByID: function(userId) {
      return console.log("This is the userId: " + userId);
    }
  };
});
